### ISSUE TITLE
请问sign算法现在还是可用的么

### ISSUE THREAD

**Issue by mafulong** [SmileSmith/tiny-red-book#2]

**Comment by mafulong** [comment]
你的代码里是抓微信小程序的吧，但是你sign和auto-sign都设置的空怎么会得到有效的数据的呢，是没迭代完么

**Comment by SmileSmith** [comment]
sign算法不好使了。

现在的做法是指从小程序首页获取初始化的种子数据。

1. 真实环境请求一次小红书小程序，抓包拿到auth-sign和sign
2. 填入到代码中，有效期还是蛮长的，足够获取第一版的种子数据了。

**Comment by orchestor** [comment]
我用小程序，确实发现了这两个字段。但是feed的url变了。
